### ISSUE TITLE
Update dependancies

### ISSUE THREAD

**Issue by quintusm** [Zaid-Ajaj/ClosedXML.SimpleSheets#3]
This library is dependant on outdated versions of ClosedXML. Can we update it.  I am willing to provide a pull request

**Comment by Zaid-Ajaj** [comment]
Hi there @quintusm happy to accept contributions and PRs 🙏 then I can merge and publish

**Comment by quintusm** [comment]
Hi @Zaid-Ajaj I have created pull request #4 as a base.  As noted in the pull request I update to a newer version of ClosedXml, but not newest as there are breaking changes that I will need to fix but don't understand yet.  Hopefully I will be able to create another pull request to bring SimpleSheets up to date with latest version, but I think it is already useful to integrate pull request #4

**Comment by Zaid-Ajaj** [comment]
Resolved by #5
